services:
  pong:
    build: .
    image: tonycava/pong:latest
    env_file: .env
    platform: linux/amd64
    ports:
      - "8080:80"
    restart: always
  back:
    build:
      dockerfile: Dockerfile.back
      context: .
    image: tonycava/pong-back:latest
    env_file: .env
    platform: linux/amd64
    ports:
      - "3000:3000"
    restart: always